name: Publish NuGet Package

on:
  push:
    branches:
      - master   # or your target branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore ./src/Infodoc.Medication.Contracts/Infodoc.Medication.Contracts.csproj

    - name: Build
      run: dotnet build ./src/Infodoc.Medication.Contracts/Infodoc.Medication.Contracts.csproj --configuration Release --no-restore

    - name: Pack NuGet package
      run: dotnet pack ./src/Infodoc.Medication.Contracts/Infodoc.Medication.Contracts.csproj --configuration Release --no-build -o ./nupkgs

    - name: Show GitHub repository owner
      run: echo "Repository owner is ${{ github.repository_owner }}"

    - name: List .nupkg files
      run: ls -R ./nupkgs

    - name: Push to GitHub Packages
      run: dotnet nuget push ./nupkgs/*.nupkg \
        --source "https://nuget.pkg.github.com/shrajan98/index.json" \
        --api-key ${{ secrets.GH_PAT }}

